/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rHA7ypowMU2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import {JSX,SVGProps} from "react"

export function FAQ() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="mx-auto max-w-3xl space-y-4 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Frequently Asked Questions</h2>
          <p className="text-gray-500 dark:text-gray-400">
            Get answers to the most common questions about our platform.
          </p>
        </div>
        <div className="mx-auto mt-12 max-w-3xl space-y-4">
          <Collapsible className="rounded-md border border-gray-200 bg-white shadow-sm dark:bg-gray-950 dark:border-gray-800">
            <CollapsibleTrigger className="flex w-full items-center justify-between gap-4 px-6 py-4">
              <h3 className="text-lg font-semibold">What features does your platform offer?</h3>
              <CollapsibleTrigger asChild>
                <Button size="icon" variant="ghost">
                  <ChevronDownIcon className="h-5 w-5 transition-transform duration-300 [&[data-state=open]]:rotate-180" />
                </Button>
              </CollapsibleTrigger>
            </CollapsibleTrigger>
            <CollapsibleContent className="border-t border-gray-200 px-6 py-4 dark:border-gray-800">
              <p className="text-gray-500 dark:text-gray-400">
                Our platform offers a wide range of features to help you build and deploy your web applications. This
                includes automated CI/CD, built-in testing, integrated collaboration tools, and more. We&apos;re constantly
                adding new features based on customer feedback, so check our roadmap for the latest updates.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="rounded-md border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-950">
            <CollapsibleTrigger className="flex w-full items-center justify-between gap-4 px-6 py-4">
              <h3 className="text-lg font-semibold">How secure is your platform?</h3>
              <CollapsibleTrigger asChild>
                <Button size="icon" variant="ghost">
                  <ChevronDownIcon className="h-5 w-5 transition-transform duration-300 [&[data-state=open]]:rotate-180" />
                </Button>
              </CollapsibleTrigger>
            </CollapsibleTrigger>
            <CollapsibleContent className="border-t border-gray-200 px-6 py-4 dark:border-gray-800">
              <p className="text-gray-500 dark:text-gray-400">
                Security is our top priority. We use industry-leading encryption and authentication methods to protect
                your data. Our platform is also regularly audited and tested to ensure compliance with the latest
                security standards.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="rounded-md border border-gray-200 bg-white shadow-sm dark:bg-gray-950 dark:border-gray-800">
            <CollapsibleTrigger className="flex w-full items-center justify-between gap-4 px-6 py-4">
              <h3 className="text-lg font-semibold">What kind of support do you offer?</h3>
              <CollapsibleTrigger asChild>
                <Button size="icon" variant="ghost">
                  <ChevronDownIcon className="h-5 w-5 transition-transform duration-300 [&[data-state=open]]:rotate-180" />
                </Button>
              </CollapsibleTrigger>
            </CollapsibleTrigger>
            <CollapsibleContent className="border-t border-gray-200 px-6 py-4 dark:border-gray-800">
              <p className="text-gray-500 dark:text-gray-400">
                We offer a variety of support options to help you get the most out of our platform. This includes 24/7
                email and chat support, a comprehensive knowledge base, and a community forum where you can connect with
                other users and our team of experts.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="rounded-md border border-gray-200 bg-white shadow-sm dark:bg-gray-950 dark:border-gray-800">
            <CollapsibleTrigger className="flex w-full items-center justify-between gap-4 px-6 py-4">
              <h3 className="text-lg font-semibold">How much does your platform cost?</h3>
              <CollapsibleTrigger asChild>
                <Button size="icon" variant="ghost">
                  <ChevronDownIcon className="h-5 w-5 transition-transform duration-300 [&[data-state=open]]:rotate-180" />
                </Button>
              </CollapsibleTrigger>
            </CollapsibleTrigger>
            <CollapsibleContent className="border-t border-gray-200 px-6 py-4 dark:border-gray-800">
              <p className="text-gray-500 dark:text-gray-400">
                We offer a range of pricing plans to fit the needs of businesses of all sizes. Our basic plan starts at
                $99 per month, with additional features and support available in our higher-tier plans. We also offer
                custom enterprise pricing for larger organizations. You can check our pricing page for more details.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="rounded-md border border-gray-200 bg-white shadow-sm dark:bg-gray-950 dark:border-gray-800">
            <CollapsibleTrigger className="flex w-full items-center justify-between gap-4 px-6 py-4">
              <h3 className="text-lg font-semibold">How easy is it to get started with your platform?</h3>
              <CollapsibleTrigger asChild>
                <Button size="icon" variant="ghost">
                  <ChevronDownIcon className="h-5 w-5 transition-transform duration-300 [&[data-state=open]]:rotate-180" />
                </Button>
              </CollapsibleTrigger>
            </CollapsibleTrigger>
            <CollapsibleContent className="border-t border-gray-200 px-6 py-4 dark:border-gray-800">
              <p className="text-gray-500 dark:text-gray-400">
                We&apos;ve designed our platform to be as user-friendly and straightforward as possible. Our onboarding
                process is simple and guided, with plenty of documentation and tutorials to help you get up and running
                quickly. Our team is also available to provide personalized support and training to ensure a smooth
                transition.
              </p>
            </CollapsibleContent>
          </Collapsible>
        </div>
      </div>
    </section>
  )
}

function ChevronDownIcon(props: JSX.IntrinsicAttributes&SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}
