/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TpaKPcujoR3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function TestimonialSection() {
  return (
    <section className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto px-4 py-12">
      <div className="col-span-1 md:col-span-2">
        <h2 className="text-3xl font-bold mb-4 text-center">What Our Customers Are Saying</h2>
      </div>
      <div className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-950">
        <div className="p-6">
          <blockquote className="text-lg font-medium text-gray-900 dark:text-gray-50">
            “The customer service I received was exceptional. The support team went above and beyond to address my
            concerns.”
          </blockquote>
          <div className="flex items-center mt-6 space-x-3">
            <div className="flex-shrink-0">
              <img
                alt="Avatar"
                className="rounded-full"
                height={48}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width={48}
              />
            </div>
            <div>
              <div className="text-base font-semibold text-gray-900 dark:text-gray-50">Jules Winnfield</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">CEO, Acme Inc</div>
            </div>
          </div>
        </div>
      </div>
      <div className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-950">
        <div className="p-6">
          <blockquote className="text-lg font-medium text-gray-900 dark:text-gray-50">
            “I&apos;ve been using this product for months and it has completely transformed my workflow. Highly recommended!”
          </blockquote>
          <div className="flex items-center mt-6 space-x-3">
            <div className="flex-shrink-0">
              <img
                alt="Avatar"
                className="rounded-full"
                height={48}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width={48}
              />
            </div>
            <div>
              <div className="text-base font-semibold text-gray-900 dark:text-gray-50">Mia Wallace</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">Product Manager, Globex Corp</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
