/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MsxK3nIIRr7
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  CardTitle,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import AddBlog from "../AddBlog";
import { auth } from "@/utils/auth";
import { prisma } from "@/utils/prisma";

export async function UserDashboard() {
  const session = await auth();
  if (!session) return <div className="flex justify-center">LOGIN FIRST</div>;

  const blogSites = await prisma.blogSite.findMany({
    where: {
      subscribers: {
        has: session.user?.email as string,
      },
    },
  });
  return (
    <main className="container mx-auto px-4 py-8 space-y-8">
      <AddBlog email={session.user?.email as string} />
      <div className="grid lg:grid-cols-2 gap-6">
        {blogSites.map((site) => (
          <Card key={site.id}>
            <CardHeader>
              <CardTitle>
                {" "}
                {site.name ?? `${site.url} Waiting For Admin Approval`}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-2">
                <div>
                  <h3 className="font-medium">Latest Article</h3>
                  <p>{site.latestBlogTitle}</p>
                </div>
                <div className="text-gray-500 dark:text-gray-400">
                  <span>Published on </span>
                  <time dateTime="2023-05-22">
                    {site.latestBlogDate?.toLocaleDateString()}
                  </time>
                </div>
              </div>
            </CardContent>
            <CardFooter className="flex items-center justify-end gap-2">
              <a
                href={site.latestBlogUrl as string}
                target="_blank"
                rel="noopener noreferrer"
              >
                {" "}
                <Button size="sm">Read The Article</Button>
              </a>
              <Button size="sm" variant="outline">
                Delete Site
              </Button>
            </CardFooter>
          </Card>
        ))}
      </div>
    </main>
  );
}
